apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: demo-frontend
  namespace: demo
spec:
  provider: nginx
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-frontend
  # ingress reference
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: http-ingress
  # HPA reference (optional)
  # autoscalerRef:
  #   apiVersion: autoscaling/v2
  #   kind: HorizontalPodAutoscaler
  #   name: demo-frontend

  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # ClusterIP port number
    port: 8080
    # container port number or name
    targetPort: 8080
  analysis:
    # schedule interval (default 60s)
    interval: 10s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    # NGINX Prometheus checks
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: 99
      interval: 2m
    # testing (optional)
    webhooks:
      - name: "flagger load test"
        type: rollout
        url: http://flagger-loadtester.default/
        timeout: 3s
        metadata:
          cmd: "hey -z 120s -q 10 -c 2 http://demo-frontend-canary.default.svc.cluster.local:8080"

# Hey
# -z Tiempo de la prueba
# -q Cantidad de hits
# -c Usuarios concurrentes
